swagger: "2.0"

info:
  title: "Intranet document shelf"
  version: "1.0"

basePath: /v1.0

consumes:
  - application/json

paths:
  /documents:
    get:
      tags: [Documents]
      operationId: documents.document.get_documents
      summary: fetch all documents
      produces:
        - application/json
      responses:
        200:
          description: Return documents
          schema:
            type: array
            items:
              $ref: '#/definitions/document'
    post:
      tags: [Documents]
      operationId: documents.document.post_document
      summary: create new document
      parameters:
        - in: body
          name: document
          required: true
          schema:
            $ref: '#/definitions/document'
      responses:
        '201':
          description: 'new document'
  
  '/documents/{id}':
    get:
      tags: [Documents]
      operationId: documents.document.get_document
      summary: fetch document with id
      parameters:
      - in: path
        name: id
        required: true
        type: string
      responses:
        '200':
          description: 'return document'
          schema:
            $ref: '#/definitions/document'
        '404':
          description: 'document does not exist'

  '/documents/descriptions/{id}':
    get:
      tags: [Abstract]
      operationId: documents.document.get_description
      summary: description of document with id
      parameters:
      - in: path
        name: id
        required: true
        type: string
      responses:
        '200':
          description: 'description document'
          schema:
            $ref: '#/definitions/beschreibung'

  '/documents/descriptions':
    get:
      tags: [Abstract]
      operationId: documents.document.get_descriptions
      summary: description of all document
      responses:
        '200':
          description: 'description document'
          schema:
            type: array
            items:
              $ref: '#/definitions/beschreibung'

definitions:
  beschreibung:
    type: object
    properties:
      beschreibung:
        type: string

  document:
    type: object
    properties:
      name:
        type: string
        description: document name
        example: "Important AVG document"
        minLength: 1
        maxLength: 100
      timestamp:
        type: string
        description: "creation time"
        example: "2018-03-26 18:25:27.742112"
        readOnly: true
      description:
        type: string
        example: "document abstract"
        minLength: 1
        maxLength: 100
      version:
        type: integer
        example: 1
        minLength: 1
        maxLength: 100

